FORMAT: 1A
HOST: https://api.shrikeh.net


# Army builder
Army builder API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Game
Game-related resources of the **Game API**

## Index
### List all available entry points [GET]
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/>;rel="self"
            Last-Modified: Wed, 07 Apr 2014 23:31:27 GMT

    + Body

            {
                "_links": {
                    "self": {
                        "href": "/",
                        "title": "Army builder index"
                    },
                    "curies": [{
                        "name": "army-builder",
                        "href": "https://api.shrikeh.net/docs/{rel}",
                        "templated": true
                    }],
                    "army-builder:status": {
                        "title": "Status",
                        "href": "/status"
                    },
                    "army-builder:games": {
                        "title": "Games",
                        "href": "/games"
                    },
                    "army-builder:manufacturers": {
                        "title": "Manufacturers",
                        "href": "/manufacturers"
                    }
                }
            }

## Games Collection [/games]
### List all available games[GET]
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/games>;rel="self"
            Last-Modified: Wed, 07 Apr 2014 23:31:27 GMT

    + Body

            {
                "_links": {
                    "self": {
                        "href": "/games",
                        "title": "Games"
                    },
                    "curies": [{
                        "name": "games",
                        "href": "https://api.shrikeh.net/docs/{rel}",
                        "templated": true
                    }],
                    "games:game": {
                        "title": "Games",
                        "href": "/games/{game}",
                        "templated": true
                    }
                }
            }

## Game [/games/{game}]
A single Game resource with all its details.
The Game resource has the following attributes:

- name
- description
+ Parameters
    + game (required, game, `infinity`) ... String `game` of the Game to query. Has example value.
    
+ Model (application/hal+json)

    HAL+JSON representation of Game Resource. In addition to representing its state in the JSON form it offers affordances in the form of the HTTP Link header and HAL links.
    + Headers
    
            Link: <https://api.shrikeh.net/infinity/>;rel="self"
            Last-Modified: Wed, 07 Jul 2010 23:31:27 GMT

    + Body
    
            { 
                "name": "Infinity",
                "description": "Infinity is a game with 28mm high metal miniatures that simulates combat and special operations in a science fiction environment with Manga aesthetics. Infinity miniatures are characterized by the high quality and detail of their modeling, the dynamism of their postures and their futuristic aesthetic.",
                "_links": {
                    "self": {
                        "href": "/games/infinity"
                    },
                    "factions": {
                        "href": "/games/infinity/factions"
                    }
                },
                "_embedded": {
                    "manufacturers": [{
                        "_links": {
                            "self": {
                                "href": "/manufacturers/corvus-belli"
                            }
                        },
                        "name": "Corvus Belli",
                        "website": "http://www.infinitythegame.com",
                        "description": "Corvus Belli puts history and fantasy in your hands. Corvus Belli designs and manufacture s miniatures in white metal for collectors, painters, wargamers and role-playing games players. The miniatures are supplied without painting."
                    }]
                }
            }

### Show a Game [GET]
+ Response 200
    [Game][]
    
### Edit a Game [PATCH]
+ Request (application/json)

        {
            "description": "New description"
        }
        
+ Response 204

### Delete a Game [DELETE]
+ Response 204

# Group Faction
Faction related resources of the **Factions API**
## Factions Collection [/games/{game}/factions]
### List all Factions [GET]
+ Parameters
    + game (required, game, `infinity`) ... String `game` of the Game to query for factions. Has example value.
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/games/infinity/factions>;rel="self"
            Last-Modified: Wed, 07 Jul 2010 23:31:27 GMT

    + Body 
    
            {
                "_links": {
                    "self": {
                        "href": "/games/infinity/factions"
                    },
                },
                "_embedded": {
                    "groupings": [
                    {
                        "name": "Human Sphere",
                        "_links": {
                            "self": {
                                "href": "/games/infinity/factions/human-sphere"
                            },
                            "haqqislam": {
                                "href": "/games/infinity/factions/haqqislam"
                                "name": "Haqqislam"
                            },
                            "panoceania": {
                                "href": "/games/infinity/factions/panoceania",
                                "name": "PanOceania"
                            },
                            "aleph": {
                                "href": "/games/infinity/factions/aleph"
                                "name": "Aleph"
                            },
                            "yu-jing": {
                                "href": "/games/infinity/factions/yu-jing"
                                "name": "Yu Jing"
                            },
                            "ariadna": {
                                "href": "/games/infinity/factions/ariadna"
                                "name": "Ariadna"
                            }
                        }
                    },
                    {
                        "name": "Combined Army",
                        "_links": {
                            "self": {
                                "href": "/games/infinity/factions/combined-army"
                            }
                        },
                        "_embedded": {
                            "armies": [{
                                "_links": {
                                    "self": {
                                        "href": "/games/infinity/factions/combined-army/armies"
                                    }
                                }
                            }]
                        }
                    },
                    {
                        "name": Tohaa",
                        "_links": {
                            "self": {
                                "href": "/games/infinity/factions/tohaa"
                            }
                        },
                        "_embedded": {
                            "armies": [{
                                "_links": {
                                    "self": {
                                        "href": "/games/infinity/factions/tohaa/armies"
                                    }
                                }
                            }]
                        }
                    }]
                }
            }
            

## Faction [/games/{game}/factions/{faction}]
A single Faction object with all its details

+ Parameters
    + game (required, game, `dust-warfare`) ... String `game` of the Game to query for factions. Has example value.
    + faction (required, faction, `ssu`) ... String `faction` of the Faction to perform action with. Has example value.
+ Model (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/games/dust-warfare/factions/ssu>;rel="self"
            Last-Modified: Wed, 07 Jul 2010 23:31:27 GMT

    + Body

            {
                "_links": {
                    "self": {
                        "href": "/games/dust-warfare/factions/ssu"
                    },
                    "units": {
                        "href": "/games/dust-warfare/factions/ssu/units"
                    }
                },
                "name": "Sino-Soviet Union",
                "abbreviation": "SSU"
            }
            
### Retrieve a Faction [GET]
+ Response 200 (application/hal+json)
    [Faction][]

# Group Unit
Unit-related resources of the **Units API**
## Units Collection [/games/{game}/units]
### List all Units [GET]
+ Parameters
    + game (required, game, `infinity`) ... String `game` of the Game to query for Units. Has example value.
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/games/infinity/units>;rel="self"
            Last-Modified: Wed, 07 Jul 2010 23:31:27 GMT

    + Body  

            [{
                "_links": {
                    "self": {
                        "href": "/games/infinity/units"
                    },            
            }]