FORMAT: 1A
HOST: https://api.shrikeh.net


# Army builder
Army builder API is a *short texts saving* service similar to its physical paper presence on your table.

## Army Builder API Root [/]
Army builder API entry point.

This resource does not have any attributes. Instead it offers the initial API affordances in the form of the HTTP Link header and HAL links.
## Retrieve Entry Point [GET]
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/>;rel="self"
            Last-Modified: Wed, 07 Apr 2014 23:31:27 GMT

    + Body

            {
                "_links": {
                    "self": {
                        "title": "Army builder index",
                        "href": "/"
                    },
                    "curies": [{
                        "name": "army-builder",
                        "href": "https://api.shrikeh.net/docs/{rel}",
                        "templated": true
                    }],
                    "army-builder:status": {
                        "title": "Status",
                        "href": "/status"
                    },
                    "army-builder:systems": {
                        "title": "Systems",
                        "href": "/systems"
                    },
                    "army-builder:system": {
                        "href": "/systems/{system}",
                        "templated": true
                    }
                    "army-builder:manufacturers": {
                        "title": "Manufacturers",
                        "href": "/manufacturers"
                    }
                }
            }

# Group System
Game system-related resources of the **System API**

## System Collection [/systems{?embed}]

Entry point to list game systems.                 
+ Parameters

    + embed (optional, string) ... What resources to embed (if any). Comma-separated list.

### GET
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/systems>;rel="self"
            Last-Modified: Wed, 07 Apr 2014 23:31:27 GMT

    + Body

            {
                "_links": {
                    "self": {
                        "href": "/systems",
                        "title": "Game Systems"
                    },
                    "curies": [{
                        "name": "systems",
                        "href": "https://api.shrikeh.net/docs/{rel}",
                        "templated": true
                    }],
                    "systems:infinity": {
                        "href": "/systems/infinity",
                        "title": "Infinity"
                    },
                    "systems:dust-warfare": {
                        "href": "/systems/dust-warfare",
                        "title": "Dust Warfare"
                    }
                }
            }

### GET /systems?embed=game
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/systems?embed=system;rel="self"
            Last-Modified: Wed, 07 Apr 2014 23:31:27 GMT

    + Body

            {
                "_links": {
                    "self": {
                        "href": "/systems?embed=game",
                        "title": "Game Systems"
                    },
                    "curies": [{
                        "name": "systems",
                        "href": "https://api.shrikeh.net/docs/{rel}",
                        "templated": true
                    }]
                },
                "_embedded": {
                    "infinity" : {
                        "name": "Infinity",
                        "description": "Infinity is a game with 28mm high metal miniatures that simulates combat and special operations in a science fiction environment with Manga aesthetics. Infinity miniatures are characterized by the high quality and detail of their modeling, the dynamism of their postures and their futuristic aesthetic.",
                        "_links": {
                            "self": {
                                "href": "/systems/infinity"
                            },
                            "factions": {
                                "href": "/systems/infinity/factions"
                            }
                        }
                    },
                    "dust-warfare" : {
                        "name": "Dust Warfare",
                        "description": "Infinity is a game with 28mm high metal miniatures that simulates combat and special operations in a science fiction environment with Manga aesthetics. Infinity miniatures are characterized by the high quality and detail of their modeling, the dynamism of their postures and their futuristic aesthetic.",
                        "_links": {
                            "self": {
                                "href": "/systems/dust-warfare"
                            },
                            "factions": {
                                "href": "/systems/dust-warfare/factions"
                            }
                        }
                    }
                }
            }

### GET /games?embed=game.factions
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/games?embed=game.factions;rel="self"
            Last-Modified: Wed, 07 Apr 2014 23:31:27 GMT

    + Body

            {
                "_links": {
                    "self": {
                        "href": "/system?embed=system.factions",
                        "title": "Game Systems"
                    }
                },
                "_embedded": {
                    "infinity" : {
                        "name": "Infinity",
                        "description": "Infinity is a game with 28mm high metal miniatures that simulates combat and special operations in a science fiction environment with Manga aesthetics. Infinity miniatures are characterized by the high quality and detail of their modeling, the dynamism of their postures and their futuristic aesthetic.",
                        "_links": {
                            "self": {
                                "title": "Infinity",
                                "href": "/systems/infinity"
                            }
                        },
                        "_embedded": {
                            "combined-army": {
                                "name": "Combined Army",
                                "_links": {
                                    "self": {
                                        "title": "Combined Army",
                                        "href": "/systems/infinity/factions/combined-army"
                                    }
                                }
                            },
                            "tohaa": {
                                "name": "Tohaa",
                                "_links": {
                                    "self": {
                                        "title": "Tohaa",
                                        "href": "/systems/infinity/factions/tohaa"
                                    }
                                }
                            }
                        }
                    },
                    "dust-warfare" : {
                        "name": "Dust Warfare",
                        "description": "Infinity is a game with 28mm high metal miniatures that simulates combat and special operations in a science fiction environment with Manga aesthetics. Infinity miniatures are characterized by the high quality and detail of their modeling, the dynamism of their postures and their futuristic aesthetic.",
                        "_links": {
                            "self": {
                                "title": "Dust Warfare",
                                "href": "/systems/dust-warfare"
                            }
                        },
                        "_embedded": {
                            "allies": {
                                "name": "Allies",
                                "_links": {
                                    "self": {
                                        "title": "Allies",
                                        "href": "/systems/dust-warfare/factions/allies"
                                    }
                                }  
                            },
                            "axis": {
                                "name": "Axis",
                                "_links": {
                                    "self": {
                                        "title": "Axis",
                                        "href": "/systems/dust-warfare/factions/axis"
                                    }
                                }
                            },
                            "ssu": {
                                "name": "Sino-Soviet Union",
                                "_links": {
                                    "self": {
                                        "title": "SSU",
                                        "href": "/systems/dust-warfare/factions/ssu"
                                    }
                                }
                            }
                        }
                    }
                }
            }

## Game [/systems/{system}]
A single System resource with all its details.
The System resource has the following attributes:

- name
- description
+ Parameters
    + system (required, system, `infinity`) ... String `system` of the System to query. Has example value.
    
+ Model (application/hal+json)
    HAL+JSON representation of System Resource. In addition to representing its state in the JSON form it offers affordances in the form of the HTTP Link header and HAL links.
    + Headers
    
            Link: <https://api.shrikeh.net/system/infinity/>;rel="self"
            Last-Modified: Wed, 07 Jul 2010 23:31:27 GMT

    + Body
    
            { 
                "name": "Infinity",
                "description": "Infinity is a game with 28mm high metal miniatures that simulates combat and special operations in a science fiction environment with Manga aesthetics. Infinity miniatures are characterized by the high quality and detail of their modeling, the dynamism of their postures and their futuristic aesthetic.",
                "_links": {
                    "self": {
                        "title": "Infinity",
                        "href": "/systems/infinity"
                    },
                    "factions": {
                        "title": "Infinity: Factions"
                        "href": "/systems/infinity/factions"
                    }
                },
                "_embedded": {
                    "manufacturers": [{
                        "_links": {
                            "self": {
                                "title": "Corvus Belli",
                                "href": "/manufacturers/corvus-belli"
                            }
                        },
                        "name": "Corvus Belli",
                        "website": "http://www.corvusbelli.com",
                        "description": "Corvus Belli puts history and fantasy in your hands. Corvus Belli designs and manufacture s miniatures in white metal for collectors, painters, wargamers and role-playing games players. The miniatures are supplied without painting."
                    }]
                }
            }

### Show a Game [GET]
+ Response 200
    [Game][]
    
### Edit a Game [PATCH]
+ Request (application/json)

        {
            "description": "New description"
        }
        
+ Response 200
    [Game][]

### Delete a Game [DELETE]
+ Response 204

# Group Faction
Faction related resources of the **Factions API**
## Factions Collection [/systems/{system}/factions]
### List all Factions [GET]
+ Parameters
    + system (required, system, `infinity`) ... String `system` of the System to query for factions. Has example value.
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/system/infinity/factions>;rel="self"
            Last-Modified: Wed, 07 Jul 2010 23:31:27 GMT

    + Body 
    
            {
                "_links": {
                    "self": {
                        "title": "Infinity: Factions",
                        "href": "/system/infinity/factions"
                    },
                },
                "_embedded": {
                    "groupings": [
                    {
                        "name": "Human Sphere",
                        "_links": {
                            "self": {
                                "title": "Human Sphere",
                                "href": "/systems/infinity/factions/human-sphere",
                            },
                            "haqqislam": {
                                "title": "Haqqislam",
                                "href": "/systems/infinity/factions/haqqislam"
                            },
                            "panoceania": {
                                "title": "PanOceania",
                                "href": "/systems/infinity/factions/panoceania"
                            },
                            "aleph": {
                                "title": "Aleph",
                                "href": "/systems/infinity/factions/aleph"
                            },
                            "yu-jing": {
                                "title": "Yu Jing",
                                "href": "/systems/infinity/factions/yu-jing"
                            },
                            "ariadna": {
                                "title": "Ariadna",
                                "href": "/systems/infinity/factions/ariadna"
                            }
                        }
                    },
                    {
                        "name": "Combined Army",
                        "_links": {
                            "self": {
                                "title": "Combined Army",
                                "href": "/system/infinity/factions/combined-army"
                            }
                        },
                        "_embedded": {
                            "armies": [{
                                "_links": {
                                    "self": {
                                        "href": "/systems/infinity/factions/combined-army/armies"
                                    }
                                }
                            }]
                        }
                    },
                    {
                        "name": Tohaa",
                        "_links": {
                            "self": {
                                "title": "Tohaa",
                                "href": "/systems/infinity/factions/tohaa"
                            }
                        },
                        "_embedded": {
                            "armies": [{
                                "_links": {
                                    "self": {
                                        "href": "/systems/infinity/factions/tohaa/armies"
                                    }
                                }
                            }]
                        }
                    }]
                }
            }
            

## Faction [/systems/{system}/factions/{faction}]
A single Faction object with all its details

+ Parameters
    + system (required, system, `dust-warfare`) ... String `system` of the System to query for factions. Has example value.
    + faction (required, faction, `ssu`) ... String `faction` of the Faction to perform action with. Has example value.
+ Model (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/systems/dust-warfare/factions/ssu>;rel="self"
            Last-Modified: Wed, 07 Jul 2010 23:31:27 GMT

    + Body

            {
                "_links": {
                    "self": {
                        "title": "Sino-Soviet Union"
                        "href": "/systems/dust-warfare/factions/ssu"
                    },
                    "units": {
                        "title": "Sino-Soviet Union: Units",
                        "href": "/systems/dust-warfare/factions/ssu/units"
                    }
                },
                "name": "Sino-Soviet Union",
                "abbreviation": "SSU"
            }
            
### Retrieve a Faction [GET]
+ Response 200 (application/hal+json)
    [Faction][]

# Group Unit
Unit-related resources of the **Units API**
## Units Collection [/systems/{system}/units]
### List all Units [GET]
+ Parameters
    + system (required, system, `infinity`) ... String `system` of the System to query for Units. Has example value.
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/systems/infinity/units>;rel="self"
            Last-Modified: Wed, 07 Jul 2010 23:31:27 GMT

    + Body  

            [{
                "_links": {
                    "self": {
                        "title": "Infinity: Units",
                        "href": "/systems/infinity/units"
                    },            
            }]