FORMAT: 1A
HOST: https://api.shrikeh.net

# Army builder
Army builder API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Games
Game-related resources of the **Games API**

## Games Collection [/]
### List all Games [GET]
+ Response 200 (application/hal+json)
    + Headers
    
            Link: <https://api.shrikeh.net/>;rel="self"

    + Body
    
            { 
            "_links": {
                    "self": {
                        "href": "/"
                    }
                },
                "_embedded": {
                    "infinity": {
                        "name": "Infinity",
                        "description": "Infinity is a game with 28mm high metal miniatures that simulates combat and special operations in a science fiction environment with Manga aesthetics. Infinity miniatures are characterized by the high quality and detail of their modeling, the dynamism of their postures and their futuristic aesthetic.",
                        "_links": {
                            "self": {
                                "href": "/infinity"
                            },
                            "factions": {
                                "href": "/infinity/factions"
                            }
                        }
                    },
                    "x-wing": {
                        "name": "X-Wing",
                        "description": "Control the most advanced starfighters and outstanding pilots in the galaxy! In X-Wing Miniatures Game, you take the role of squad leader and command a group of merciless Imperial or daring Rebel pilots in furious ship-to-ship space combat. Featuring stunningly detailed and painted miniatures, X-Wing recreates exciting Star Wars space battles from small engagements of only a couple of crafts, to large conflicts where multiple squadrons clash. Select and equip your ships, pick your crew, plan your attack, and complete your mission.",
                        "_links": {
                            "self": {
                                "href": "/x-wing"
                            },
                            "factions": {
                                "href": "/x-wing/factions"
                            }
                        }
                    },
                    "dust-warfare: {
                        "name": "Dust Warfare",
                        "description": Dust Warfare is a tabletop wargame designed by Andy Chambers and Mack Martin in which players take command of elite soldiers, awesome combat walkers, and inspiring heroes on the battlefronts of World War II. In this accessible and thrilling game, opposing generals craft strategies and execute tactics as they fight for victory.\n\nIn Dust Warfare, you’ll build and customize an army and lead them in engaging and interactive battles. Hand-select your forces for each engagement, and deploy them in intense missions that test your skill as a field commander. With its flexible rules, you can interrupt your opponent’s turn, reacting to his movements or attacks. Feign assaults, outsmart the enemy, and lure him into exposing his plans.",
                        "_links": {
                            "self": {
                                "href": "/dust-warfare"
                            },
                            "factions": {
                                "href": "/dust-warfare/factions"
                            }
                        }
                    }
                }
            }
            
# Group Faction
Faction related resources of the **Factions API**

## Factions Collection [{game}/factions]
### List all Factions [GET]
+ Response 200 (application/hal+json)
+ Parameters
    + game (required, game, `infinity`) ... String `game` of the Game to query for factions. Has example value.
    
    + Headers
    
            Link: <https://api.shrikeh.net/infinity/factions>;rel="self"
    + Body          
    
            [{
                "name": "Human Sphere",
                
                "_links": {
                    "self": {
                        "href": "/infinity/factions/human-sphere"
                    },
                    "children": [{
                        "href": "/infinity/factions/haqqislam"
                        "name": "Haqqislam",
                        "logo": "haqqislam.png"
                    },
                    {
                        "href": "/infinity/factions/panoceania"
                        "name": "PanOceania",
                        "logo": "panoceania.png"
                    },
                    {
                        "href": "/infinity/factions/aleph"
                        "name": "Aleph",
                        "logo": "aleph.png"
                    },
                    {
                        "href": "/infinity/factions/yu-jing"
                        "name": "Yu Jing",
                        "logo": "yu-jing.png"
                    },
                    {
                        "href": "/infinity/factions/ariadna"
                        "name": "Ariadna",
                        "logo": "ariadna.png"
                    }]
                }
            },
            {
                "name": "Combined Army",
                "_links": {
                    "self": {
                        "href": "/infinity/factions/combined-army"
                    }
                },
                "_embedded": {
                    "armies": [{
                        "_links": {
                            "self": {
                                "href": "/infinity/factions/combined-army/armies"
                            }
                        }
                    }]
                }
            },
            {
                "name": Tohaa",
                "_links": {
                    "self": {
                        "href": "/infinity/factions/tohaa"
                    }
                },
                "_embedded": {
                    "armies": [{
                        "_links": {
                            "self": {
                                "href": "/infinity/factions/tohaa/armies"
                            }
                        }
                    }]
                }
            }]

### Create a Faction [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/hal+json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [{game}/factions/{faction}]
A single Faction object with all its details

+ Parameters
    + game (required, game, `dust-warfare`) ... String `game` of the Game to query for factions. Has example value.
    + faction (required, faction, `ssu`) ... String `faction` of the Faction to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/hal+json)

    
    + Headers
            Link: <https://api.shrikeh.net/dust-warfare/factions/ssu>;rel="self"

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
